
name: Build and Push Docker Image

on:
 # push:
 #   branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/examportal:latest
    
    - name: Install Trivy
      run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.40.0_Linux-64bit.deb

    - name: Run Trivy scan on Docker image
      run: trivy image --no-progress ghcr.io/${{ github.repository_owner }}/examportal:latest
    - name: Upload Trivy scan report as artifact
      uses: actions/upload-artifact@v3
      with:
          name: trivy-scan-report
          path: trivy-report.json
    - name: List directory contents for debugging
      run: ls -alh
    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/examportal:latest
